//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18047
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.DeviceService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DeviceService.IDeviceService")]
    public interface IDeviceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeviceService/CheckRegistration", ReplyAction="http://tempuri.org/IDeviceService/CheckRegistrationResponse")]
        bool CheckRegistration(string uniqueIdentifier, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeviceService/CheckRegistration", ReplyAction="http://tempuri.org/IDeviceService/CheckRegistrationResponse")]
        System.Threading.Tasks.Task<bool> CheckRegistrationAsync(string uniqueIdentifier, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeviceService/GetById", ReplyAction="http://tempuri.org/IDeviceService/GetByIdResponse")]
        DataContracts.Device GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeviceService/GetById", ReplyAction="http://tempuri.org/IDeviceService/GetByIdResponse")]
        System.Threading.Tasks.Task<DataContracts.Device> GetByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeviceService/GetAll", ReplyAction="http://tempuri.org/IDeviceService/GetAllResponse")]
        System.Collections.Generic.List<DataContracts.Device> GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeviceService/GetAll", ReplyAction="http://tempuri.org/IDeviceService/GetAllResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DataContracts.Device>> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeviceService/Register", ReplyAction="http://tempuri.org/IDeviceService/RegisterResponse")]
        void Register(string type, string uniqueIdentifier, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeviceService/Register", ReplyAction="http://tempuri.org/IDeviceService/RegisterResponse")]
        System.Threading.Tasks.Task RegisterAsync(string type, string uniqueIdentifier, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeviceService/Update", ReplyAction="http://tempuri.org/IDeviceService/UpdateResponse")]
        void Update(DataContracts.Device device);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeviceService/Update", ReplyAction="http://tempuri.org/IDeviceService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(DataContracts.Device device);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeviceService/Delete", ReplyAction="http://tempuri.org/IDeviceService/DeleteResponse")]
        void Delete(string uniqueIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeviceService/Delete", ReplyAction="http://tempuri.org/IDeviceService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string uniqueIdentifier);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDeviceServiceChannel : DataAccess.DeviceService.IDeviceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeviceServiceClient : System.ServiceModel.ClientBase<DataAccess.DeviceService.IDeviceService>, DataAccess.DeviceService.IDeviceService {
        
        public DeviceServiceClient() {
        }
        
        public DeviceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeviceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeviceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeviceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CheckRegistration(string uniqueIdentifier, int userId) {
            return base.Channel.CheckRegistration(uniqueIdentifier, userId);
        }
        
        public System.Threading.Tasks.Task<bool> CheckRegistrationAsync(string uniqueIdentifier, int userId) {
            return base.Channel.CheckRegistrationAsync(uniqueIdentifier, userId);
        }
        
        public DataContracts.Device GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public System.Threading.Tasks.Task<DataContracts.Device> GetByIdAsync(int id) {
            return base.Channel.GetByIdAsync(id);
        }
        
        public System.Collections.Generic.List<DataContracts.Device> GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DataContracts.Device>> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public void Register(string type, string uniqueIdentifier, int userId) {
            base.Channel.Register(type, uniqueIdentifier, userId);
        }
        
        public System.Threading.Tasks.Task RegisterAsync(string type, string uniqueIdentifier, int userId) {
            return base.Channel.RegisterAsync(type, uniqueIdentifier, userId);
        }
        
        public void Update(DataContracts.Device device) {
            base.Channel.Update(device);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(DataContracts.Device device) {
            return base.Channel.UpdateAsync(device);
        }
        
        public void Delete(string uniqueIdentifier) {
            base.Channel.Delete(uniqueIdentifier);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string uniqueIdentifier) {
            return base.Channel.DeleteAsync(uniqueIdentifier);
        }
    }
}
