//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.UserProductsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserProductsService.IUserProductsService")]
    public interface IUserProductsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProductsService/GetByUserId", ReplyAction="http://tempuri.org/IUserProductsService/GetByUserIdResponse")]
        System.Collections.Generic.List<DataContracts.UserProducts> GetByUserId(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProductsService/GetByUserId", ReplyAction="http://tempuri.org/IUserProductsService/GetByUserIdResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DataContracts.UserProducts>> GetByUserIdAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProductsService/GetById", ReplyAction="http://tempuri.org/IUserProductsService/GetByIdResponse")]
        DataContracts.UserProducts GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProductsService/GetById", ReplyAction="http://tempuri.org/IUserProductsService/GetByIdResponse")]
        System.Threading.Tasks.Task<DataContracts.UserProducts> GetByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProductsService/GetAll", ReplyAction="http://tempuri.org/IUserProductsService/GetAllResponse")]
        System.Collections.Generic.List<DataContracts.UserProducts> GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProductsService/GetAll", ReplyAction="http://tempuri.org/IUserProductsService/GetAllResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DataContracts.UserProducts>> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProductsService/Insert", ReplyAction="http://tempuri.org/IUserProductsService/InsertResponse")]
        void Insert(DataContracts.UserProducts entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProductsService/Insert", ReplyAction="http://tempuri.org/IUserProductsService/InsertResponse")]
        System.Threading.Tasks.Task InsertAsync(DataContracts.UserProducts entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProductsService/Update", ReplyAction="http://tempuri.org/IUserProductsService/UpdateResponse")]
        void Update(DataContracts.UserProducts entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProductsService/Update", ReplyAction="http://tempuri.org/IUserProductsService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(DataContracts.UserProducts entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProductsService/Delete", ReplyAction="http://tempuri.org/IUserProductsService/DeleteResponse")]
        void Delete(DataContracts.UserProducts entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProductsService/Delete", ReplyAction="http://tempuri.org/IUserProductsService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(DataContracts.UserProducts entity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserProductsServiceChannel : DataAccess.UserProductsService.IUserProductsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserProductsServiceClient : System.ServiceModel.ClientBase<DataAccess.UserProductsService.IUserProductsService>, DataAccess.UserProductsService.IUserProductsService {
        
        public UserProductsServiceClient() {
        }
        
        public UserProductsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserProductsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserProductsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserProductsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<DataContracts.UserProducts> GetByUserId(int userId) {
            return base.Channel.GetByUserId(userId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DataContracts.UserProducts>> GetByUserIdAsync(int userId) {
            return base.Channel.GetByUserIdAsync(userId);
        }
        
        public DataContracts.UserProducts GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public System.Threading.Tasks.Task<DataContracts.UserProducts> GetByIdAsync(int id) {
            return base.Channel.GetByIdAsync(id);
        }
        
        public System.Collections.Generic.List<DataContracts.UserProducts> GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DataContracts.UserProducts>> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public void Insert(DataContracts.UserProducts entity) {
            base.Channel.Insert(entity);
        }
        
        public System.Threading.Tasks.Task InsertAsync(DataContracts.UserProducts entity) {
            return base.Channel.InsertAsync(entity);
        }
        
        public void Update(DataContracts.UserProducts entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(DataContracts.UserProducts entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(DataContracts.UserProducts entity) {
            base.Channel.Delete(entity);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(DataContracts.UserProducts entity) {
            return base.Channel.DeleteAsync(entity);
        }
    }
}
